pipeline:
  docker:
    image: plugins/docker
    registry: registry.labs.0x.no
    repo: registry.labs.0x.no/env
    dockerfile: .dockerfile
    tags:
      - latest
  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
  # tests to ensure they compile independently
  test-neovim:
    group: test
    image: alpine:latest
    commands:
      - ./.install/neovim.sh
      - nvim -version
      - nvim +checkhealth +qa
  test-pure:
    group: test
    image: alpine:latest
    commands:
      - ./.install/pure.sh
  test-thefuck:
    group: test
    image: alpine:latest
    commands:
      - ./.install/thefuck.sh
      - thefuck -v
  test-yadm:
    group: test
    image: alpine:latest
    commands:
      - ./.install/yadm.sh
      - yadm version
  test-golang:
    group: test
    image: alpine:latest
    commands:
      - ./.install/golang.sh
      - go version
      - go get github.com/golang/example/hello
      - $HOME/go/bin/hello
  test-node:
    group: test
    image: alpine:latest
    commands:
      - ./.install/node.sh
      - node -e "console.log(process.versions)"
      - yarn --version
  test-python:
    group: test
    image: alpine:latest
    commands:
      - ./.install/python.sh
      - python3 --version
      - pip3 --version
  test-jdk:
    group: test
    image: alpine:latest
    commands:
      - ./.install/jdk.sh
      - java -version
  test-kubectl:
    group: test
    image: alpine:latest
    commands:
      - ./.install/kubectl.sh
      - kubectl version -c
