pipeline:
  docker:
    image: plugins/docker
    registry: registry.labs.0x.no
    repo: registry.labs.0x.no/env
    dockerfile: .dockerfile
    tags:
      - latest
  test-neovim:
    image: alpine:latest
    commands:
      - ./.install/neovim.sh
  test-yadm:
    image: alpine:latest
    commands:
      - ./.install/yadm.sh
  test-golang:
    image: alpine:latest
    commands:
      - ./.install/golang.sh
  test-node:
    image: alpine:latest
    commands:
      - ./.install/node.sh
  test-kubectl:
    image: alpine:latest
    commands:
      - ./.install/kubectl.sh



