pipeline:
  docker:
    image: plugins/docker
    registry: registry.labs.0x.no
    repo: registry.labs.0x.no/env
    dockerfile: .dockerfile
    tags:
      - latest
  # tests to ensure they compile independently
  test-neovim:
    group: test
    image: alpine:latest
    commands:
      - ./.install/neovim.sh
      - nvim -version
      - nvim +checkhealth +qa
  test-yadm:
    group: test
    image: alpine:latest
    commands:
      - ./.install/yadm.sh
      - yadm version
  test-golang:
    group: test
    image: alpine:latest
    commands:
      - ./.install/golang.sh
      - export PATH=/usr/local/go/bin:$PATH
      - go version
      - go get github.com/golang/example/hello
      - $HOME/go/bin/hello
  test-node:
    group: test
    image: alpine:latest
    commands:
      - ./.install/node.sh
      - node -e "console.log(process.versions)"
  test-kubectl:
    group: test
    image: alpine:latest
    commands:
      - ./.install/kubectl.sh
      - kubectl version -c
  test-jdk:
    group: test
    image: alpine:latest
    commands:
      - ./.install/jdk.sh
      - export PATH=/usr/local/jdk/bin:$PATH
      - java -version
