kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    registry: registry.makerforce.io
    repo: registry.makerforce.io/ambrose/env
    dockerfile: .dockerfile
    tags:
    - latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
  when:
    status: [ failure, success ]

---
kind: pipeline
name: test-neovim
steps:
- name: test-neovim
  image: alpine:latest
  commands:
  - apk add --no-cache patch
  - ./.install/neovim-source.sh
  - nvim -version
  - nvim +checkhealth +qa
- name: test-plug
  image: alpine:latest
  commands:
  - ./.install/repositories.sh
  - apk add --no-cache neovim@community
  - ./.install/core.sh
  - ./.install/plug.sh
---
kind: pipeline
name: test-python
steps:
- name: test-python
  image: alpine:latest
  commands:
  - ./.install/python.sh
  - python3 --version
  - pip3 --version
---
kind: pipeline
name: test-golang
steps:
- name: test-golang
  image: alpine:latest
  commands:
  - ./.install/golang-source.sh
  - go version
- name: test-packr
  image: golang:1.13-alpine
  commands:
  - ./.install/git.sh
  - ./.install/upx.sh
  - ./.install/packr.sh
- name: test-caddy
  image: golang:1.13-alpine
  commands:
  - apk add --no-cache build-base
  - ./.install/git.sh
  - ./.install/upx.sh
  - ./.install/caddy.sh
---
kind: pipeline
name: test-node
steps:
- name: test-node
  image: alpine:latest
  commands:
  - ./.install/node-source.sh
  - node -e "console.log(process.versions)"
- name: test-yarn
  image: alpine:latest
  commands:
  - ./.install/node-source.sh
  - ./.install/core.sh
  - ./.install/gnupg.sh
  - ./.install/yarn.sh
  - ~/.local/bin/yarn --version
---
kind: pipeline
name: test-jdk
steps:
- name: test-jdk
  image: alpine:latest
  commands:
  - ./.install/jdk.sh
  - java -version
---
kind: pipeline
name: test-dircolors
steps:
- name: test-dircolors
  image: alpine:latest
  commands:
  - ./.install/core.sh
  - ./.install/dircolors.sh
---
kind: pipeline
name: test-dust
steps:
- name: test-dust
  image: alpine:latest
  commands:
  - ./.install/core.sh
  - ./.install/dust.sh
---
kind: pipeline
name: test-pure
steps:
- name: test-pure
  image: alpine:latest
  commands:
  - ./.install/core.sh
  - ./.install/pure.sh
---
kind: pipeline
name: test-thefuck
steps:
- name: test-thefuck
  image: alpine:latest
  commands:
  - ./.install/python.sh
  - ./.install/sudo.sh
  - ./.install/thefuck.sh
  - ~/.local/bin/thefuck -v
---
kind: pipeline
name: test-zsh-autosuggestions
steps:
- name: test-zsh-autosuggestions
  image: alpine:latest
  commands:
  - ./.install/git.sh
  - ./.install/zsh-autosuggestions.sh
---
kind: pipeline
name: test-zsh-syntax-highlighting
steps:
- name: test-zsh-syntax-highlighting
  image: alpine:latest
  commands:
  - ./.install/git.sh
  - ./.install/zsh-syntax-highlighting.sh
---
kind: pipeline
name: test-yadm
steps:
- name: test-yadm
  image: alpine:latest
  commands:
  - ./.install/core.sh
  - ./.install/git.sh
  - ./.install/yadm.sh
  - ~/.local/bin/yadm version
---
kind: pipeline
name: test-pass
steps:
- name: test-pass
  image: alpine:latest
  commands:
  - ./.install/repositories.sh
  - ./.install/sudo.sh
  - ./.install/pass.sh
  - pass version
---
kind: pipeline
name: test-httpie
steps:
- name: test-httpie
  image: alpine:latest
  commands:
  - ./.install/python.sh
  - ./.install/httpie.sh
  - ~/.local/bin/http --version
---
kind: pipeline
name: test-jq
steps:
- name: test-jq
  image: alpine:latest
  commands:
  - ./.install/core.sh
  - ./.install/upx.sh
  - ./.install/jq.sh
  - ~/.local/bin/jq --version
---
kind: pipeline
name: test-kubectl
steps:
- name: test-kubectl
  image: alpine:latest
  commands:
  - ./.install/core.sh
  - ./.install/upx.sh
  - ./.install/kubectl.sh
  - ~/.local/bin/kubectl version --client
---
kind: pipeline
name: test-minio-client
steps:
- name: test-minio-client
  image: alpine:latest
  commands:
  - ./.install/core.sh
  - ./.install/upx.sh
  - ./.install/minio-client.sh
  - ~/.local/bin/mc version
